# ============================================================
# PRODUCTION ENVIRONMENT CONFIGURATION
# ============================================================

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Mail credentials
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# Supabase credentials
supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}

# JWT Secret
jwt.secret=${JWT_SECRET}

# Swagger UI
springdoc.swagger-ui.enabled=false

# Logging
logging.level.com.ride.mate.config=WARN
logging.level.com.ride.mate.controller=INFO
logging.level.org.springframework.security=WARN

# Multipart file upload limits
spring.servlet.multipart.max-file-size= ${MULTIPART_MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${MULTIPART_MAX_REQUEST_SIZE}
spring.servlet.multipart.resolve-lazily= true

# PayHere Payment Gateway Configuration
payhere.api-base-url=${PAYHERE_API_BASE_URL}
payhere.api.charge-path=${PAYHERE_API_CHARGE_PATH}

payhere.merchant-id=${PAYHERE_MERCHANT_ID}
payhere.merchant-secret=${PAYHERE_MERCHANT_SECRET}
