# ============================================================
# LOCAL ENVIRONMENT CONFIGURATION
# ============================================================

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/ride_mate_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=password

# Mail credentials
spring.mail.username=info.ridemate@gmail.com
spring.mail.password=zjew pntc gocy rstk

# Supabase credentials
supabase.url=https://zmpnxjkifkvhikozwcga.supabase.co
supabase.key=sb_secret_Q6hBRMAsL9_Kt-Hj78KUoA_twkLhrsn

# JWT Secret
jwt.secret=RideMateSecretKey2026ForJWTAuthenticationTokenGenerationAndValidation

# Swagger UI enabled in local
springdoc.swagger-ui.enabled=true

# Logging - verbose in local
logging.level.com.ride.mate.config=DEBUG
logging.level.com.ride.mate.controller=DEBUG
logging.level.org.springframework.security=DEBUG

# Multipart file upload limits
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.resolve-lazily=true

# PayHere Payment Gateway Configuration
payhere.api-base-url=https://sandbox.payhere.lk
payhere.api.charge-path=/merchant/v2/charge

payhere.merchant-id=1234563
payhere.merchant-secret=NTUwMDQ3OTg0MTcyMTQ4MDM1NTcxMDE5NzM0NzMxMTIyMzA3NjQ=

# Commission Configuration
ride-mate.commission.default-percentage=5

# Ml Service Configuration
mlServiceBaseUrl=http://localhost:8000

# Redis Configuration (for real-time driver location tracking only)
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.timeout=5000ms
